### 注册接口

POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
  "nickname": "测试用户2",
  "phone": "17775336644",
  "password": "123456"
}

### 登录接口

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "phone": "17775336644",
  "password": "123456"
}