### 注册接口

POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
  "nickname": "测试用户2",
  "phone": "17775336644",
  "password": "123456"
}

### 登录接口

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "phone": "17775336644",
  "password": "123456"
}

### 创建文集接口

POST http://localhost:3000/api/note/notebook HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTQwNjQsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTUwNDY0fQ.r149Da-ibWUWlOhd8rsbzlWQEumIAKsdM-53BLC7bqs

{
  "name": "我的文集5"
}

### 修改文集接口
PUT http://localhost:3000/api/note/notebook HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTQwNjQsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTUwNDY0fQ.r149Da-ibWUWlOhd8rsbzlWQEumIAKsdM-53BLC7bqs

{
  "id": 1,
  "name": "我的文集1修改"
}

### 获取用户文集接口
GET http://localhost:3000/api/note/notebook HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTQwNjQsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTUwNDY0fQ.r149Da-ibWUWlOhd8rsbzlWQEumIAKsdM-53BLC7bqs

### 删除文集接口
DELETE http://localhost:3000/api/note/notebook HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTQwNjQsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTUwNDY0fQ.r149Da-ibWUWlOhd8rsbzlWQEumIAKsdM-53BLC7bqs

{
  "id": 3
}

### 获取所有文集接口
GET http://localhost:3000/api/notebooks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTQwNjQsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTUwNDY0fQ.r149Da-ibWUWlOhd8rsbzlWQEumIAKsdM-53BLC7bqs

### 创建文章接口

POST http://localhost:3000/api/note/note HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTk0ODAsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTU1ODgwfQ.b2TPa3ccneuk7VUtykb8ebN5ewdLHf8pGikwmh6eaTE

{
  "notebookId": 1
}

### 修改文章接口

PUT http://localhost:3000/api/note/note HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTk0ODAsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTU1ODgwfQ.b2TPa3ccneuk7VUtykb8ebN5ewdLHf8pGikwmh6eaTE

{
  "noteId": 3,
  "title": "我的文章3",
  "content_md": "我的文章3内容",
  "state": 1
}

### 获取用户文章接口

GET http://localhost:3000/api/note/note?page=1&pageSize=2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NTk0ODAsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTU1ODgwfQ.b2TPa3ccneuk7VUtykb8ebN5ewdLHf8pGikwmh6eaTE

### 删除文章接口
DELETE http://localhost:3000/api/note/note HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NjI5NTIsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTU5MzUyfQ.QhsFXNvpktr8dTvaelClg4OfofjGxs2tZV_naZan_yA

{
  "noteId": 2
}

### 获取所有文章接口

GET http://localhost:3000/api/note/note?page=1&pageSize=2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA1NjI5NTIsImRhdGEiOnsiZGF0YSI6eyJ1aWQiOjN9fSwiaWF0IjoxNzcwNTU5MzUyfQ.QhsFXNvpktr8dTvaelClg4OfofjGxs2tZV_naZan_yA
